language: python
python:
  - "2.6"
  - "2.7"
env:
  - FLASK=dev
  - FLASK=0.9
  - FLASK=0.8
install:
  - pip install flask==$FLASK --use-mirrors
  - pip install -r pip-requirements.txt
script:
  - python weight/tests/maintest.py
